version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb2
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
    networks:
      - mongodb-network
    command: mongod --quiet --logpath /dev/null #used to disable logging
  back:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    volumes:
      - ./:/app/
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - front
    networks:
      - mongodb-network
    command: ["sh", "-c", "cd backend && npm install && npm run dev"]
  front:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
    networks:
      - mongodb-network
    command: ["sh", "-c", "cd frontend && npm install --legacy-peer-deps && npm run dev"]
networks:
  mongodb-network:
    driver: bridge
