version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - mongodb-network
  app:
    image: promptdesk/promptdesk:latest
    environment:
      - MONGO_URL=mongodb://mongodb:27017/app
    depends_on:
      - mongodb
    networks:
      - mongodb-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www/:/var/www/certbot
      - ./certbot/conf/:/etc/letsencrypt
    ports:
      - "8080:80"
      # - "80:80"
      # - "443:443"
    depends_on:
      - app
    networks:
      - mongodb-network
  # certbot:
  #   image: certbot/certbot:latest
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot
  #     - ./certbot/conf/:/etc/letsencrypt
networks:
  mongodb-network:
    driver: bridge