name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.MONGO_URL }}
      - run: echo ${{ secrets.OPENAI_API_KEY }}
      - run: echo ${{ vars.NODE_ENV }}
      - run: echo ${{ env.GITHUB_SHA_SHORT }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
        working-directory: ./backend
      - name: Run tests
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NODE_ENV: ${{ vars.NODE_ENV }}
        run: npm run test
        working-directory: ./backend
